services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    working_dir: /workspace
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: todo_app
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongodb_data:/data/db
    # healthcheck:
    #   test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 30

